runtime: python39

env_variables:
  MYSQL_USER: '[USUARIO]'
  MYSQL_PASSWORD: '[CONTRASEÑA]'
  MYSQL_DATABASE: '[NOMBRE_DE_LA_BASE_DE_DATOS]'
  MYSQL_HOST: '{IP_DATABASE}'
  MYSQL_PORT: '{PUERTO}'
  CLOUD_SQL_CONNECTION_NAME: '[NOMBRE_DE_LA_INSTANCIA_DE_CLOUD_SQL]'
