runtime: python39

env_variables:
  cloud_sql_host: HOST_PUBLICA
  db_password: CONTRASEÑA
  db_user:  USUARIO_SQL
  db_name:  NOMBRE_DATABASE
  db_port:  3306
  CLOUD_SQL_CONNECTION_NAME: mibodaangelywendy:us-central1:guests-wedding

vpc_access_connector:
  name: "projects/mibodaangelywendy/locations/us-central1/connectors/connect-to-sql"